
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '12.0'

target 'Example' do
   pod 'SHWHeZhouVideoTemplate', :path => '../'
#  pod 'SHWHeZhouVideoTemplate', :git => 'https://github.com/newsdata/SHWVideoTemplate.git', :tag => '1.0.1'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|

    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end

